include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = IconTransparencyPrefs
IconTransparencyPrefs_FILES = IconTransparencyPrefs.mm
IconTransparencyPrefs_INSTALL_PATH = /Library/PreferenceBundles
IconTransparencyPrefs_FRAMEWORKS = UIKit
IconTransparencyPrefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
